import { Market } from './market.interface';
import { Currency } from './currency.interface';
import { Info } from './info.interface';

export interface OrderStatus {
  id: number;
  wallet_group: any;
  service: string;
  market: Market;
  amount1: string;
  amount2: string;
  price: string;
  price_limit: string;
  price_stop: any;
  price_limit_oco: any;
  type: string;
  active_limit: string;
  identifier: string;
  mode: string;
  expected_gain: string;
  expected_resource: string;
  commission_percent: number;
  user_share_percent: number;
  expected_commission: string;
  expected_user_gain: string;
  expected_user_price: string;
  gain_currency: Currency;
  resource_currency: Currency;
  fulfilled: number;
  exchanged1: string;
  exchanged2: string;
  gain: string;
  resource: string;
  remain_amount: string;
  average_price: string;
  average_user_price: string;
  commission: string;
  user_commission: string;
  user_gain: string;
  created_at: string;
  activated_at: string;
  state: string;
  req_to_cancel: boolean;
  info: Info;
  closed_at: any;
  external_address: string;
}
