name: Release

on:
  push:
    branches:
      - master

permissions:
  id-token: 'write'
  contents: 'read'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Package Version Updated
        uses: MontyD/package-json-updated-action@1.0.1
        id: version-updated
        with:
          path: package.json
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: 'Checkout source code'
        if: steps.version-updated.outputs.has-updated
        uses: actions/checkout@v4

      - name: Create GitHub release
        if: steps.version-updated.outputs.has-updated
        uses: Roang-zero1/github-create-release-action@v3
        with:
          created_tag: v${{ steps.version-updated.outputs.current-package-version }}
          changelog_file: CHANGELOG.md
          changelog_heading: h2
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
